export const NOTIFICATION_ROADMAP = [
  { id: 'webhook-delivery',        status: 'done' },
  { id: 'email-smtp',              status: 'done' },
  { id: 'zalo-oa-api',             status: 'done' },
  { id: 'zns-template-messaging',  status: 'done' },
  { id: 'multi-tenant-zalo-oa',    status: 'done' },
  { id: 'zalo-webhook-receiver',   status: 'done' },
  { id: 'zalo-quota-monitoring',   status: 'done' },
  { id: 'sms-vonage',              status: 'done' },
  { id: 'template-engine',         status: 'done' },
  { id: 'template-crud',           status: 'done' },
  { id: 'delivery-tracking',       status: 'done' },
  { id: 'notification-logs-ui',    status: 'done' },
  { id: 'retry-with-backoff',      status: 'done' },
  { id: 'batch-delivery',          status: 'done' },
  { id: 'slack-integration',       status: 'done' },
  { id: 'push-notification',       status: 'pending' },
  { id: 'signal-encryption',       status: 'pending' },
];
