/**
 * PayPal Gateway SDK — HTTP Controller.
 *
 * Exposes endpoints under `/payments/paypal`:
 *
 *   POST   /payments/paypal/create-order   — Create a PayPal order (returns approval URL)
 *   POST   /payments/paypal/webhook        — PayPal IPN webhook (post-back verify)
 *   GET    /payments/paypal/verify/:orderId — Active reconciliation (safety net)
 *   POST   /payments/paypal/reconcile      — Manual reconcile & fallback activation
 *   GET    /payments/paypal/return         — User redirect after PayPal approval
 *
 * Security:
 *   - /create-order is tenant-authenticated (tenantId from auth context, NOT
 *     client-supplied body) to prevent IDOR attacks.
 *   - /webhook is protected by PayPal's POST-back signature verification
 *     (no session auth needed — PayPal IPN is server-to-server).
 *   - /verify and /reconcile are authenticated via auth context for IDOR safety.
 */

import {
  Controller,
  Post,
  Get,
  Param,
  Body,
  Headers,
  Query,
  Req,
  HttpCode,
  HttpStatus,
  Logger,
  BadRequestException,
  UnauthorizedException,
} from '@nestjs/common';
import type { Request } from 'express';
import { PayPalService } from './paypal.service';
import { PayPalConfig } from './paypal.config';
import { PrismaService } from '../../prisma.service';
import type {
  PayPalCreateOrderInput,
  PayPalWebhookEvent,
  PayPalWebhookHeaders,
  PayPalWebhookResult,
  PayPalVerificationResult,
} from './paypal.types';

/** Minimal shape for the POST /create-order body. */
interface CreateOrderDto {
  /** Internal order ID (AIFUT-xxx) — pre-generated by caller. */
  orderId: string;
  /** Amount in smallest internal unit (BigInt as string to preserve precision). */
  amount: string;
  /** ISO 4217 currency code (USD, THB, VND…). Defaults to PAYPAL_CURRENCY env. */
  currency?: string;
  /** Human-readable description (max 127 chars). */
  description?: string;
  /** URL to redirect after PayPal approval. Must be HTTPS in production. */
  returnUrl: string;
  /** URL to redirect if user cancels. */
  cancelUrl: string;
}

/** Body for the POST /reconcile endpoint. */
interface ReconcileBody {
  orderId: string;
  paypalOrderId: string;
  gatewayTxId?: string;
}

/** Response envelope consistent across all endpoints. */
interface PayPalApiResponse {
  success: boolean;
  data?: Record<string, unknown>;
  error?: string;
}

/**
 * Resolve tenantId from the auth context to prevent IDOR attacks.
 * In production, replace with a shared AuthGuard / session middleware.
 */
function resolveTenantId(req: Request): string {
  const fromContext =
    (req as any).user?.tenantId ??
    (req.headers['x-tenant-id'] as string | undefined);
  if (fromContext && typeof fromContext === 'string' && fromContext.length > 0) {
    return fromContext;
  }
  throw new UnauthorizedException('Không thể xác định tenant. Vui lòng đăng nhập.');
}

@Controller('payments/paypal')
export class PayPalController {
  private readonly logger = new Logger(PayPalController.name);

  constructor(
    private readonly paypalService: PayPalService,
    private readonly paypalConfig: PayPalConfig,
    private readonly prisma: PrismaService,
  ) {}

  // --------------------------------------------------------------------------
  // POST /payments/paypal/create-order
  // --------------------------------------------------------------------------

  /**
   * Create a PayPal Order (intent=CAPTURE) and return the approval URL.
   *
   * The caller must pre-create a PaymentTransaction record (status=pending)
   * via the payments service BEFORE calling this endpoint. The body's orderId
   * is used as the transaction reference.
   *
   * Tenant identity is resolved from the auth context, preventing IDOR.
   */
  @Post('create-order')
  @HttpCode(HttpStatus.OK)
  async createOrder(
    @Body() dto: CreateOrderDto,
    @Req() req: Request,
  ): Promise<PayPalApiResponse> {
    // ---- Validate inputs ---------------------------------------------------
    if (!dto.orderId || typeof dto.orderId !== 'string' || dto.orderId.length === 0) {
      throw new BadRequestException('orderId is required');
    }
    if (!dto.amount || isNaN(Number(dto.amount)) || Number(dto.amount) <= 0) {
      throw new BadRequestException(
        'amount must be a positive number string (internal smallest unit)',
      );
    }
    if (!dto.returnUrl || typeof dto.returnUrl !== 'string') {
      throw new BadRequestException('returnUrl is required');
    }
    if (!dto.cancelUrl || typeof dto.cancelUrl !== 'string') {
      throw new BadRequestException('cancelUrl is required');
    }

    // ---- Resolve tenant from auth context (IDOR prevention) ------------------
    let tenantId: string;
    try {
      tenantId = resolveTenantId(req);
    } catch (err) {
      throw new UnauthorizedException((err as Error).message);
    }

    // ---- Check PayPal is configured ------------------------------------------
    if (!this.paypalConfig.isConfigured) {
      this.logger.warn('PayPal gateway not configured, cannot create order');
      throw new BadRequestException(
        'PayPal gateway chưa được cấu hình. Vui lòng liên hệ quản trị viên.',
      );
    }

    // ---- Build input & delegate ----------------------------------------------
    const input: PayPalCreateOrderInput = {
      orderId: dto.orderId,
      tenantId,
      amount: BigInt(dto.amount),
      currency:
        dto.currency?.toUpperCase() ??
        this.paypalConfig.tryGet()?.defaultCurrency ??
        'USD',
      description: dto.description ?? 'Thanh toán AIFUT PayPal',
      returnUrl: dto.returnUrl,
      cancelUrl: dto.cancelUrl,
      ipAddress:
        (req.headers['x-forwarded-for'] as string)
          ?.split(',')[0]
          ?.trim() ??
        req.socket?.remoteAddress ??
        '0.0.0.0',
    };

    const result = await this.paypalService.createPayPalOrder(input);

    if (!result.success) {
      return {
        success: false,
        error: result.errorMessage ?? 'Tạo đơn hàng PayPal thất bại',
      };
    }

    return {
      success: true,
      data: {
        paypalOrderId: result.paypalOrderId,
        approvalUrl: result.approvalUrl,
        orderId: result.orderId,
        amount: result.amount.toString(),
        currency: result.currency,
      },
    };
  }

  // --------------------------------------------------------------------------
  // POST /payments/paypal/webhook
  // --------------------------------------------------------------------------

  /**
   * PayPal IPN Webhook endpoint.
   *
   * PayPal sends webhook events server-to-server when payment status changes.
   * This endpoint:
   *   1. Extracts PayPal signature headers for POST-back verification.
   *   2. Delegates to PayPalService.handlePayPalWebhook() which performs
   *      full POST-back verify, idempotency claim, settle, and activation.
   *   3. Always returns 200 OK to PayPal — even on errors — so PayPal does
   *      NOT retry into a broken handler. Errors are logged server-side.
   *
   * No session auth — PayPal webhooks are server-to-server HTTP callbacks.
   * Security is via the POST-back signature verification.
   */
  @Post('webhook')
  @HttpCode(HttpStatus.OK)
  async handleWebhook(
    @Headers() headers: Record<string, string>,
    @Body() body: PayPalWebhookEvent,
  ): Promise<Record<string, unknown>> {
    // Extract PayPal-specific headers.
    const paypalHeaders: PayPalWebhookHeaders = {
      'paypal-transmission-id': headers['paypal-transmission-id'] ?? '',
      'paypal-transmission-sig': headers['paypal-transmission-sig'] ?? '',
      'paypal-cert-url': headers['paypal-cert-url'] ?? '',
      'paypal-auth-algo': headers['paypal-auth-algo'] ?? '',
      'paypal-transmission-time': headers['paypal-transmission-time'],
    };

    // Quick validation: transmission-id must be present.
    if (!paypalHeaders['paypal-transmission-id']) {
      this.logger.warn('PayPal webhook missing transmission-id header');
      return { status: 1, message: 'Missing PayPal signature headers' };
    }

    if (!body?.event_type) {
      this.logger.warn('PayPal webhook missing event_type in body');
      return { status: 1, message: 'Missing event_type' };
    }

    try {
      const result: PayPalWebhookResult =
        await this.paypalService.handlePayPalWebhook(paypalHeaders, body);

      this.logger.log(
        `PayPal webhook processed event=${body.id} type=${body.event_type} ` +
          `received=${result.received} matched=${result.matched} ` +
          `settled=${result.settled} activated=${result.activated}`,
      );

      return {
        status: 0,
        message: 'OK',
        eventType: result.eventType,
        matched: result.matched,
        settled: result.settled,
        activated: result.activated,
      };
    } catch (err) {
      // Never throw in webhook — always return 200 so PayPal stops retrying.
      this.logger.error(
        `PayPal webhook handler error event=${body?.id}: ${(err as Error).message}`,
      );
      return {
        status: 1,
        message: 'Internal error processing webhook',
      };
    }
  }

  // --------------------------------------------------------------------------
  // GET /payments/paypal/verify/:paypalOrderId
  // --------------------------------------------------------------------------

  /**
   * Active reconciliation — query PayPal directly for an order's current state.
   *
   * Safety net for dropped webhook deliveries. The frontend (or a cron job)
   * can call this after the user returns from the PayPal approval flow to
   * "catch up" the local state with PayPal's side.
   *
   * If the capture is COMPLETED but local state is still pending, this
   * endpoint triggers the full settle+activate flow automatically.
   *
   * Protected by tenant auth context (IDOR prevention via x-tenant-id).
   */
  @Get('verify/:paypalOrderId')
  async verifyOrder(
    @Param('paypalOrderId') paypalOrderId: string,
    @Req() req: Request,
  ): Promise<PayPalApiResponse> {
    if (!paypalOrderId || paypalOrderId.length === 0) {
      throw new BadRequestException('paypalOrderId is required');
    }

    // Resolve tenant from auth context for IDOR protection.
    try {
      resolveTenantId(req);
    } catch (err) {
      throw new UnauthorizedException((err as Error).message);
    }

    const result: PayPalVerificationResult =
      await this.paypalService.verifyPayPalOrder(paypalOrderId);

    return {
      success: result.verified,
      data: {
        paypalOrderId: result.paypalOrderId,
        paypalOrderStatus: result.paypalOrderStatus,
        captureStatus: result.captureStatus,
        grossAmount: result.grossAmount,
        netAmount: result.netAmount,
        paypalFee: result.paypalFee,
        currency: result.currency,
        amountMatch: result.amountMatch,
        reconciled: result.reconciled,
      },
      error: !result.verified ? (result.errorMessage ?? 'Verification failed') : undefined,
    };
  }

  // --------------------------------------------------------------------------
  // POST /payments/paypal/reconcile
  // --------------------------------------------------------------------------

  /**
   * Manual reconciliation — safety net for IPN drops.
   *
   * Triggers the full verify+settle+activate flow for a known order.
   * Uses verifyPayPalOrder internally (which handles the claim→settle→activate
   * path when PayPal reports COMPLETED).
   *
   * In production, guard behind an AdminGuard or internal API key.
   */
  @Post('reconcile')
  @HttpCode(HttpStatus.OK)
  async reconcile(
    @Body() body: ReconcileBody,
    @Req() req: Request,
  ): Promise<PayPalApiResponse> {
    const { orderId, paypalOrderId } = body;

    if (!paypalOrderId || typeof paypalOrderId !== 'string') {
      throw new BadRequestException('paypalOrderId is required');
    }

    // Auth check for IDOR prevention.
    try {
      resolveTenantId(req);
    } catch (err) {
      throw new UnauthorizedException((err as Error).message);
    }

    const verifyResult: PayPalVerificationResult =
      await this.paypalService.verifyPayPalOrder(paypalOrderId);

    if (verifyResult.reconciled) {
      return {
        success: true,
        data: {
          orderId,
          paypalOrderId: verifyResult.paypalOrderId,
          paypalOrderStatus: verifyResult.paypalOrderStatus,
          captureStatus: verifyResult.captureStatus,
          reconciled: true,
          amountMatch: verifyResult.amountMatch,
          grossAmount: verifyResult.grossAmount,
          currency: verifyResult.currency,
          message: 'Đã đối soát thành công',
        },
      };
    }

    return {
      success: verifyResult.verified,
      data: {
        orderId,
        paypalOrderId: verifyResult.paypalOrderId,
        paypalOrderStatus: verifyResult.paypalOrderStatus,
        captureStatus: verifyResult.captureStatus,
        reconciled: verifyResult.reconciled,
        amountMatch: verifyResult.amountMatch,
      },
      error: verifyResult.errorMessage ?? 'Không thể đối soát giao dịch PayPal.',
    };
  }

  // --------------------------------------------------------------------------
  // GET /payments/paypal/return
  // --------------------------------------------------------------------------

  /**
   * User redirect after PayPal approval.
   *
   * After the user approves the payment on PayPal's side, they are redirected
   * back to the return URL. This endpoint looks up the local transaction by
   * paypalOrderId (passed as `token` query param) and returns the current
   * state for the frontend.
   *
   * NOTE: The definitive settlement happens via the webhook or active reconcile.
   * Never trust the return URL alone to activate a subscription.
   */
  @Get('return')
  async handleReturn(
    @Query('token') token: string | undefined,
    @Query('PayerID') payerId: string | undefined,
    @Req() req: Request,
  ): Promise<PayPalApiResponse> {
    if (!token) {
      throw new BadRequestException('Missing token param in return URL');
    }

    // Auth check.
    try {
      resolveTenantId(req);
    } catch (err) {
      throw new UnauthorizedException((err as Error).message);
    }

    // Look up the local transaction by paypalOrderId stored in metadata.
    try {
      const tx = await this.prisma.paymentTransaction.findFirst({
        where: {
          gateway: 'paypal',
          metadata: { path: ['paypalOrderId'], equals: token },
        },
        select: { status: true, paidAt: true, gatewayTxId: true, amount: true },
        orderBy: { createdAt: 'desc' },
      });

      if (!tx) {
        return {
          success: false,
          data: { token, payerId: payerId ?? null },
          error: 'Giao dịch chưa được đồng bộ. Vui lòng đợi trong giây lát.',
        };
      }

      return {
        success: tx.status === 'success',
        data: {
          token,
          payerId: payerId ?? null,
          status: tx.status,
          paidAt: tx.paidAt?.toISOString() ?? null,
          gatewayTxId: tx.gatewayTxId,
          amount: Number(tx.amount),
        },
      };
    } catch (err) {
      this.logger.error(
        `PayPal return lookup error token=${token}: ${(err as Error).message}`,
      );
      return {
        success: false,
        data: { token, payerId: payerId ?? null },
        error: 'Không thể tra cứu trạng thái giao dịch.',
      };
    }
  }
}
