#!/bin/bash
# ============================================================
# AIFUT User Data — EC2 Bootstrap Script
# ============================================================
# This script runs on first EC2 instance launch. It:
#   1. Installs Docker, Docker Compose, and CloudWatch agent
#   2. Clones / pulls the AIFUT application
#   3. Starts the application via docker-compose
#   4. Configures CloudWatch logging
#
# Template variables (substituted by Terraform):
#   ${region_slug}  — Region identifier
#   ${environment}  — Environment name
#   ${domain}       — Web domain
#   ${api_domain}   — API domain
#   ${locale}       — Default locale
#   ${currency}     — Default currency
#   ${log_group}    — CloudWatch log group name
# ============================================================

set -euo pipefail

# ─── Logging ─────────────────────────────────────────────
exec > >(tee /var/log/aifut-bootstrap.log | logger -t aifut-bootstrap -s 2>/dev/console) 2>&1
echo "=== AIFUT Bootstrap Started: $(date) ==="

# ─── Variables ───────────────────────────────────────────
REGION="${region_slug}"
ENV="${environment}"
DOMAIN="${domain}"
API_DOMAIN="${api_domain}"
LOCALE="${locale}"
CURRENCY="${currency}"
LOG_GROUP="${log_group}"

# ─── System Updates ──────────────────────────────────────
yum update -y
yum install -y amazon-cloudwatch-agent git jq

# ─── Install Docker ──────────────────────────────────────
amazon-linux-extras install docker -y
systemctl enable docker
systemctl start docker
usermod -aG docker ec2-user

# ─── Install Docker Compose v2 ───────────────────────────
mkdir -p /usr/local/lib/docker/cli-plugins
curl -SL "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64" \
  -o /usr/local/lib/docker/cli-plugins/docker-compose
chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

# ─── Clone AIFUT Application ─────────────────────────────
mkdir -p /opt/aifut
cd /opt/aifut

# Clone if first time, otherwise pull latest
if [ -d ".git" ]; then
  git pull origin main
else
  git clone https://github.com/aifut/aifut-core.git .
fi

# Create region-specific .env
cat > /opt/aifut/.env << ENV_EOF
# AIFUT Region Configuration — Auto-generated by Terraform
REGION_SLUG=${REGION}
ENVIRONMENT=${ENV}
DOMAIN=${DOMAIN}
API_DOMAIN=${API_DOMAIN}
DEFAULT_LOCALE=${LOCALE}
DEFAULT_CURRENCY=${CURRENCY}
TZ=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/[a-z]$//')
CLOUDWATCH_LOG_GROUP=${LOG_GROUP}

# Docker Compose project
COMPOSE_PROJECT_NAME=aifut-${REGION}
ENV_EOF

# ─── Deploy Application ─────────────────────────────────
cd /opt/aifut
docker compose pull
docker compose up -d --remove-orphans

echo "=== AIFUT Bootstrap Complete: $(date) ==="
echo "Region: ${REGION}"
echo "Web: https://${DOMAIN}"
echo "API: https://${API_DOMAIN}"
