export const ADAPTER_INTERFACE_STATUSES = ['foundation', 'planned'] as const;

export const ADAPTER_INTERFACE_FOUNDATION = [
  {
    key: 'openclaw-intent-draft-interface',
    appDefinitionKey: 'openclaw',
    adapterContractKey: 'openclaw-intent-drafting',
    connectorKey: 'generic-rest',
    status: 'foundation',
    requestShape: 'IntentDraftRequest',
    responseShape: 'IntentDraftResponse',
    normalizedInputs: [
      'actor-context',
      'tenant-context',
      'workspace-context',
      'allowed-capability-scope',
      'budget-policy',
      'prompt',
    ],
    normalizedOutputs: [
      'business-goal-draft',
      'parent-workflow-draft',
      'child-workflow-draft',
      'recommendation-artifact',
      'risk-flags',
    ],
    activationPolicy: 'approval-gated-beyond-safe-scope',
    runtimeBinding: 'draft-session',
  },
  {
    key: 'n8n-runtime-artifact-interface',
    appDefinitionKey: 'n8n',
    adapterContractKey: 'n8n-runtime-handoff',
    connectorKey: 'n8n',
    status: 'foundation',
    requestShape: 'WorkflowRuntimeArtifactRequest',
    responseShape: 'WorkflowRuntimeArtifactResponse',
    normalizedInputs: [
      'child-workflow-definition',
      'mapping-profile',
      'sync-policy',
      'runtime-config-reference',
    ],
    normalizedOutputs: [
      'workflow-runtime-artifact-ref',
      'execution-run-summary',
      'health-hints',
      'runtime-state-delta',
    ],
    activationPolicy: 'operator-reviewed-runtime-activation',
    runtimeBinding: 'execution-runtime',
  },
  {
    key: 'magica-generation-job-interface',
    appDefinitionKey: 'magica',
    adapterContractKey: 'magica-generation-job',
    connectorKey: 'generic-rest',
    status: 'foundation',
    requestShape: 'GenerationJobRequest',
    responseShape: 'GenerationJobResponse',
    normalizedInputs: [
      'content-plan',
      'asset-request',
      'prompt-or-template-reference',
      'budget-policy',
    ],
    normalizedOutputs: [
      'generation-job-summary',
      'asset-record-refs',
      'cost-summary',
      'generation-status',
    ],
    activationPolicy: 'budget-and-safety-policy-checked',
    runtimeBinding: 'generation-job',
  },
  {
    key: 'affiliate-summary-sync-interface',
    appDefinitionKey: 'aff-nexovaflow',
    adapterContractKey: 'affiliate-summary-ingest',
    connectorKey: 'generic-rest',
    status: 'foundation',
    requestShape: 'AffiliateSummarySyncRequest',
    responseShape: 'AffiliateSummarySyncResponse',
    normalizedInputs: ['offer-context', 'campaign-context', 'tracking-context'],
    normalizedOutputs: [
      'affiliate-link-ref',
      'commission-summary',
      'payout-summary',
      'referral-summary',
    ],
    activationPolicy: 'read-first-commercial-ingest',
    runtimeBinding: 'commercial-summary-sync',
  },
  {
    key: 'perfex-summary-task-bridge-interface',
    appDefinitionKey: 'perfex-nexovaflow',
    adapterContractKey: 'perfex-summary-and-task-bridge',
    connectorKey: 'nexovaflow',
    status: 'foundation',
    requestShape: 'CrmSummaryTaskBridgeRequest',
    responseShape: 'CrmSummaryTaskBridgeResponse',
    normalizedInputs: [
      'connection-instance',
      'field-mapping-profile',
      'action-request',
      'approval-state-when-required',
    ],
    normalizedOutputs: [
      'lead-summary',
      'contact-summary',
      'deal-summary',
      'task-action-result',
      'note-action-result',
    ],
    activationPolicy: 'summary-first-safe-write-scope',
    runtimeBinding: 'crm-action-bridge',
  },
] as const;

export const ADAPTER_INTERFACE_ROADMAP = [
  'interface-aware-setup-defaults',
  'interface-to-runtime-binding-validation',
  'interface-versioning-and-migration-rules',
  'interface-to-connection-instance-persistence',
] as const;
